# Generated by Django 2.0.6 on 2018-06-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alcohol',
            name='Container',
            field=models.CharField(choices=[('1', 'Bottle'), ('2', 'Can'), ('3', 'Box'), ('4', 'Bag')], default='Bottle', max_length=10),
        ),
    ]
